#!/bin/bash

# Update the date in modified R files
files=$(git diff --cached --name-only --diff-filter=d | grep -E '\.(R|r)$')
for file in $files; do
    sed -i 's/^# Date: .*/# Date: '"$(date +%Y-%m-%d)"'/' "$file"
    if [ -f "$file" ]; then
        git add "$file"
    fi
done

# Remove vscode settings from staging to avoid publishing local paths
git restore --staged .vscode/settings.json

exit 0